# Docker compose of the project
#
# Change {project} to your project's name and {client} for the client's name
# Comment or remove entries not used for your project
# You may remove this comments
#

version: "3.7"
services:
  requirements:
    container_name: {client}_{project}_requirements
    build:
      context: .
      dockerfile: docker/django/ubuntu-18.04/Dockerfile
      args:
        - EXTRA_REQUIREMENTS=devel
    image: {client}_{project}_requirements
    entrypoint:
      - /bin/bash
    command: []

  db:
    container_name: {client}_{project}_db
    build:
      context: docker/postgres/ubuntu-18.04/
      dockerfile: Dockerfile
    image: {client}_{project}_db
    env_file:
     - app.env
    command: ["/bin/bash", "/app/docker/postgres/postgresql10.sh"]
    volumes:
      - .:/app
      - dbdata:/var/lib/postgresql/

  django:
    container_name: {client}_{project}_django
    depends_on:
      - db
    image: {client}_{project}_requirements
    env_file:
     - app.env
    command: ["/bin/bash", "/app/docker/scripts/wait-for-it.sh", "db:5432", "--", "/bin/bash", "/app/docker/django/runserver.sh"]
    volumes:
      - .:/app:cached
    networks:
      default:
        aliases:
          - {project}.{client}

volumes:
  dbdata:

networks:
  default:
    external:
      name: {client}
