# Docker compose of the project
#
# Change xprojectx to your project's name and xclientx for the client's name
# Comment or remove entries not used for your project
# You may remove this comments
#

version: "3.7"
services:
  requirements:
    container_name: xclientx_xprojectx_requirements
    build:
      context: .
      dockerfile: docker/django/ubuntu-18.04/Dockerfile
      args:
        - EXTRA_REQUIREMENTS=devel
    image: xclientx_xprojectx_requirements
    entrypoint:
      - /bin/bash
    command: []

  db:
    container_name: xclientx_xprojectx_db
    build:
      context: docker/postgres/ubuntu-18.04/
      dockerfile: Dockerfile
    image: xclientx_xprojectx_db
    env_file:
     - app.env
    command: ["/bin/bash", "/app/docker/postgres/postgresql10.sh"]
    volumes:
      - .:/app
      - dbdata:/var/lib/postgresql/

  django:
    container_name: xclientx_xprojectx_django
    depends_on:
      - db
    image: xclientx_xprojectx_requirements
    env_file:
     - app.env
    command: ["/bin/bash", "/app/docker/scripts/wait-for-it.sh", "db:5432", "--", "/bin/bash", "/app/docker/django/runserver.sh"]
    volumes:
      - .:/app:cached
    networks:
      default:
        aliases:
          - xprojectx.xclientx

volumes:
  dbdata:

networks:
  default:
    external:
      name: xclientx
