# Docker compose of the project
#
# Change xprojectx to your project's name and xclientx for the client's name
# Comment or remove entries not used for your project
# You may remove this comments
#

version: "3.7"
services:
  db:
    container_name: xclientx_xprojectx_db
    image: postgres:14
    env_file:
     - app.env
    volumes:
      - .:/app
      - dbdata:/var/lib/postgresql/

  django:
    container_name: xclientx_xprojectx_django
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/django/ubuntu-20.04/Dockerfile
      args:
        - EXTRA_REQUIREMENTS=devel
    image: xclientx_xprojectx_django
    env_file:
     - app.env
    command: ["/bin/bash", "/app/docker/scripts/wait-for-it.sh", "db:5432", "--", "/bin/bash", "/app/docker/django/runserver.sh"]
    volumes:
      - .:/app:cached
    # ports:
    #   - 8000:8000
    networks:
      default:
        aliases:
          - xprojectx.xclientx

volumes:
  dbdata:

networks:
  default:
    external:
      name: xclientx
